### ISSUE TITLE
Get Kathleen your username

### ISSUE THREAD

**Issue by ecwyne** [Kathleenwyne/national-parks#1]
Just write a comment below and Kathleen will be notified that you've created an account.

**Comment by vaethl** [comment]
username is vaethl, be careful there are a few vaeth(s) here. So to be sure that is a lowercase L.

**Comment by Januari** [comment]
username is Januari

**Comment by ecwyne** [comment]
@vaethl @Januari you should both have received emails with invite links. Once you accept the invitation, you'll be able to edit files in this project

**Comment by vaethl** [comment]
I do not want to change anything here. Not feeling confident in doing so. Kathleen, you seem to have done a lot of editing.  I have to ask where are we? I noticed an error on  the Yosemite page (Bird watching, has POINT REYES), I will go check and see if that is Yosemite info or PR, Then I will place the correction here.

**Comment by Januari** [comment]
I can't seem to tell if the pages are styled.  I want to add some things, but I don't know what I am looking at.  I see some CSS, but it's not showing up when I view pages.

**Comment by vaethl** [comment]
I have edited a few of the pages, making the information shorter, but doing no code to change anything. This thing is due in a few days. I have seen some pages view fine others are missing pics that were there before.  also how do we bring continuity to the site.
